### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gaurav-nelson** [tcort/markdown-link-check#104]
Thank you Thomas @tcort for creating this awesome tool. There hasn't been any update on this project for quite some time now.

Have you abandoned this project? Or are you looking for more contributors? How can we help.

**Comment by tcort** [comment]
I haven't abandoned the project. New release coming today :)

More contributors would be great. The best way to help would be to write code; create a pull request for one of the open Issues.

**Comment by NicolasMassart** [comment]
For people having the same question, I committed to help on this project by:
- tirage issues.
- review PRs (and merge).
- fix issues (try to) and push PRs.

I can only commit on effort and not on result though. So please don't blame me if your issue is not solved fast enough.

I also have access to tcort/link-check and tcort/markdown-link-extractor so we can go through the whole dependency chain

If you want to contribute, please do:
- create or comment on issues (testing and reproduce them takes time)
- push PRs to fix these issues.
- review and comment PRs.

Thank you for your help!
