### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by hmert** [tcort/markdown-link-check#124]
Some of websites are very slow. Is there an option to set timeout? [link-check](https://www.npmjs.com/package/link-check) has it.

**Comment by cadeef** [comment]
There's a theme of issues that follow the pattern "link-check supports x, MLC should support x." It seems to me a reasonable expectation of function, but current architecture demands that upstream additions features require downstream implementation.

I'm not a JavaScript dev by any means, but casual read of the code suggests MLC is a consumer of link-check's API rather than an extension. It seems natural that MLC should enhance link-check with markdown-specific methods rather than wrapping them in another layer of abstraction.

How much effort would be required to extend link-check in the class-sense instead of consuming it? I don't know the answer but it may be a good roadmap question.
