### ISSUE TITLE
Docker tags from README are missing

### ISSUE THREAD

**Issue by TriplEight** [tcort/markdown-link-check#143]
Tried `docker run -v ${PWD}:/tmp:ro --rm -i ghcr.io/tcort/markdown-link-check:<?> /tmp/README.md`
with `stable`, `3`, `3.8.3`, `v3.8.3` and the only thing that I found was `latest`. On [this page](https://github.com/users/tcort/packages/container/package/markdown-link-check) I only see the sha image tags.

With `latest` and that it cannot show `--version` I'm not sure what version I was running to confirm that https://github.com/tcort/markdown-link-check/issues/142#issuecomment-739806405 worked.

**Comment by NicolasMassart** [comment]
Sorry this Github registry is a bit new for us and the process was skipped because we only tagged instead of release.
So now it's fine, you have an image published in https://github.com/users/tcort/packages/container/package/markdown-link-check with tags `latest`, `3`, `3.8`, `3.8.5` and `stable`.
Enjoy!
@tcort we need to create release not tags alone. [Our GitHub Docker release action runs on release created event](https://github.com/tcort/markdown-link-check/blob/master/.github/workflows/release.yml#L5).

**Comment by TriplEight** [comment]
Cheers!
