### ISSUE TITLE
Relative links fail if there is a space in the path

### ISSUE THREAD

**Issue by jorisdehaes** [tcort/markdown-link-check#15]
Relative links fail if there is a name in the path.

**How to reproduce**
1. Create a test directory, so there are no space in the path. Example: `~/test_space/`
2. Create a markdown file: `A.md`, that contains a link to A.md
3. Run `markdown-link-check` on A.md: Result is `[✓] A.md`
4. Put a space in the path: Example `~/test space/`
5. Run `markdown-link-check` on A.md again. Result is `[✖] A.md`

**Comment by tcort** [comment]
I've published `markdown-link-check` version `3.1.3` which includes a fix for this.

This issue was with the [link-check](https://github.com/tcort/link-check) module. When it got the path from the link, it was URI encoded (e.g. `test%20space`). Paths passed to the [fs](https://nodejs.org/api/fs.html) module expect non-URI encoded strings, so `test%20space` does not resolve to `test space` which leads to the failed check. I've pushed a [patch](https://github.com/tcort/link-check/commit/2748a6d792ff4fb0ddd29ce83f7394ba4ec2b403) for the `link-check` module to correct this.
