### ISSUE TITLE
make markdown-link-check fail when broken link is found

### ISSUE THREAD

**Issue by belorenz** [tcort/markdown-link-check#157]
Currently using markdown-link-check in a gitlab CI pipeline. 
I'am looking for a way to make the pipeline fail if a broken link is found.
In general the pipeline fails if a commands exit code is not 0.

I guess I will get it to work with a mixture of grep-ing the output log created with tee and some additional bash magic.
But having a way to get errors returned directly would be way cleaner.

What do you think about a option like `-f --fail-on-error` which lets markdown-link-check return exit code 1 on first/any error?

**Comment by gaurav-nelson** [comment]
@belorenz Can you clarify it a bit? `markdown-link-check` does return exit code as (1) when a check fails. 
```
▶ $ cat test.md 
# Title

## Next title.

[some link](https://www.google.com)

[wrong link](https://www.google2233222.com)

▶ $ markdown-link-check test.md 

FILE: test.md
[✓] https://www.google.com
[✖] https://www.google2233222.com

2 links checked.

ERROR: 1 dead links found!
[✖] https://www.google2233222.com → Status: 0

▶ $ echo $?
1
```

**Comment by NicolasMassart** [comment]
The issue here is the use of `tee` in the pipe. Tee always returns 0 and as it's the last command in the pipe like in `markdownlink command | tee logfile` that enables to have the output on the console and in the log file at the same time (very useful).
So to check if it failed, on workaround is to grep the log file to check for errors, see [one of my project as example](https://github.com/ConsenSys/doc.common/blob/master/build_tools/package.json#L11):
```javascript
    "test:links:check": "find . -name \\*.md ! -path \"./node_modules/*\" ! -path \"./env/*\" -exec ./node_modules/markdown-link-check/markdown-link-check -v -c common/build_tools/linkchecker/link_check_conf.json {} \\; 2>&1 | tee linkchecker.out",
    "test:links:verify": "! grep -n '[✖]\\|ERROR' ./linkchecker.out",
```
This is the package.json scripts I use. First one `test:links:check` runs link checker and pipes in tee but as the output of it will always be 0, then I run `test:links:verify` on the log file and grep for errors. That's not very nice I know.

On way to prevent that is to use `set -o pipefail` bash option. It will then prevent the error to be masked by the tee command.
It doesn't require any change on the markdownlink level.
I planned to test it and see how the output is good for my own use. Feel free to tell if it suits your need too.

**Comment by belorenz** [comment]
Thanks for helping out! 
I thought I pasted my workaround here, but cannot see it anymore. Anyhow, the reason for not failing was, as you mentioned, the use of tee.
Indeed our workaround is not very beautiful but works like a charm.
Sorry for the noise :)
