### ISSUE TITLE
Github linking in private repos

### ISSUE THREAD

**Issue by saurabh2590** [tcort/markdown-link-check#18]
Hi,
we are using this awesome markdown-link-check module.
In our documentation, sometimes we are linking to github project which is on our private repo of the same organisation.
But we discovered that markdown-link-check fails in those repos specially while running on CI.
Is there any quick workaround to handle authenticated github urls?

**Comment by tcort** [comment]
This isn't a quick work around, but the best way to do it would likely be modify my [link-check](https://github.com/tcort/link-check) module to take some additional configuration.

Since we don't want to send the auth info to every link, we need some sort of per-site configuration... for github.com send XYZ, for example.org send ABC, etc. Since auth info can be in the form of headers or cookies, we need some flexibility. There could be other instances where we need to manipulate the request besides authorization.

I'm thinking something like this where we pass in a preconfigured instance of [request](https://github.com/request/request) and have regular expressions that match the URL that they get sent to:

```
opts = {
    proto: {
        http: {
            agents: {
                '^https:\/\/www.example.org/': request.defaults({ headers: { secret: 'xxx' } }),
                '^https:\/\/www.example.net/': request.defaults({ jar: cookies }),
                _default: request,
            }
        }
    }
};
```

**Comment by karfau** [comment]
What is your opinion on providing one or multiple regular expressions for URLs that should be ignored from the check?
Of course it is more like a skipped test then the way you suggested, but it might be more easy to implement and is an option for anybody that do not want to store auth data in the source repo (or configure CI to make it work).

**Comment by tcort** [comment]
A blacklist and/or a whitelist is acceptable.

**Comment by timmkrause** [comment]
I think this can be closed now?

**Comment by karfau** [comment]
Did something happen that solved the issue?

**Comment by timmkrause** [comment]
You can now configure custom HTTP headers for certain URLs (i.e. make authenticated requests).

**Comment by karfau** [comment]
Awesome, will immediatly try it out

**Comment by karfau** [comment]
My first attempt (creating an access token) failed: I couldn't find a way to add auth headers so that links to private github repos (and issues/pulls) would become valid.
Using with the curl example described [here](https://developer.github.com/v3/auth/#basic-authentication) they still deliver 404.
I guess this is because those auth tokens are not meant for normal links but for their API.
(I will give it another try on another day...)

We also have links that point to out our internal company network that needs LDAP access.
And I do not think adding credentials to the repo to make this work is a good idea.
(I know they should come from CI system instead... not sure yet how to do this with the config.json file,
dosn't sound like the right direction to me currently.)

From my current understanding #38 should fix this issue.

**Comment by timmkrause** [comment]
#38 is a workaround I would say.

As per https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line I would say this may be possible. Unfortunately I cannot test it because I do not have access to a private repo.

Here is a little guidance:

https://gist.github.com/Integralist/9482061

**Comment by karfau** [comment]
Thx for those hints!
I will try it again, but even in the gist all the examples are referring to using the API, not to check for the links of certain webpages...
And I would still be fine with the "workaround" since no Header can fix the problem of "inhouse links" not being checkable from CircleCI or Travis.

**Comment by timmkrause** [comment]
OK.

I am already working in it. Will try to finish IT this weekend and hopefully tcort likes it top and will approve it.

**Comment by karfau** [comment]
By the way, while testing I changed some links like `https://github.com/tcort/markdown-link-check/issues/18` to GFM `tcort/markdown-link-check#18` which are not checked, but become links in the rendered markdown in the github web UI ... this doesn't work for all links but maybe this also helps other people.

**Comment by timmkrause** [comment]
@karfau Is this solved by #41 / with version 3.5.0 and its "ignorePatterns" feature?

**Comment by karfau** [comment]
Yes, the issue is resolved for us! :tada:

**Comment by timmkrause** [comment]
Great to hear that, thanks!

**Comment by PeterDaveHello** [comment]
@tcort may I know the reason why my comment was deleted?
