### ISSUE TITLE
Broken since v3.7.1

### ISSUE THREAD

**Issue by PeterDaveHello** [tcort/markdown-link-check#60]
Hi @tcort,

Thanks for your effort on this awesome tool, I just found that `markdown-link-check` is now broken, in my cases, it just hangs without any output, even with `-v` & `-p` parameter, for 10 mins, 20 mins and longer, I don't know how long it'll hang but seems forever. Builds of [`nodejs/docker-node`](https://travis-ci.com/nodejs/docker-node/builds/80703281) now also failed because there is no any response from it, and it doesn't exit.

Looks like v3.6.2 still works very well, any idea?

Many thanks again!

**Comment by anchnk** [comment]
I am not a core contributor but I was trying to use this module today and stumble into the same problem. 

After investigating a bit, `git bisect` shows that commit https://github.com/tcort/markdown-link-check/commit/b00a9b1048c55b1566c93a4afd09d0cd26a4feeb is the one causing trouble.

Especially, at line [#L68](https://github.com/tcort/markdown-link-check/blob/master/markdown-link-check#L68) where the stream is created into `fs.access`'s callback. I am not exactly 100% sure what is happening under the hood but my guess is that we shouldn't rely on `fs.access` to check if the file exist before trying to create the stream.

As stated in node's documentation (https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_access_path_mode_callback), it's considered as an anti-pattern as the file can be accessed during that time creating a **race condition**.

@gaurav-nelson What do you think about it ? Do you mind if we get rid of `fs.access` and add an `error` handler on the read stream in order to gracefully handle the situation where the file does not exist ?

**Comment by gaurav-nelson** [comment]
Thanks @anchnk You are right, this should be fixed. I rushed in with a patch because of a failing script in our CI. Thanks for #61 and #62 

@tcort It would be great if you can check and apply these updates.

**Comment by tcort** [comment]
Thanks everyone! The changes were published in v3.7.2.

**Comment by PeterDaveHello** [comment]
Thank you all.
