### ISSUE TITLE
Unescaped Unicode characters in links are broken

### ISSUE THREAD

**Issue by nex3** [tcort/markdown-link-check#76]
The checker will choke on a link that contains a Unicode character that isn't manually percent-escaped, even though browsers and most other URL processors will accept it. For example, in https://en.wikipedia.org/wiki/Backus–Naur_form, the en dash is unescaped and will cause an error.

**Comment by NicolasMassart** [comment]
Issue is at the [Request](https://www.npmjs.com/package/request) dependency level.
[Request is deprecated and will never be updated or fixed](https://github.com/request/request/issues/3142).
Migrating to a [new supported library](https://github.com/request/request/issues/3143) that handles unicode is the way.

However, even if MLC uses request as a dependency, and it should be replaced, this error on link is caused by the request used in the other project https://github.com/tcort/link-check.
I will create the corresponding issue in this repos.
