### ISSUE TITLE
Quiet mode should have not display files without errors

### ISSUE THREAD

**Issue by guivinson** [tcort/markdown-link-check#77]
The objective is to see nothing if there is no error (an not all the files checked (current behavior))

**Comment by guivinson** [comment]
I'm a bad js developer, but in algorithm, it gives something like:

1. Replacing all console.log and keep messages in memory instead.
1. The function runMarkdownLinkCheck would return the list of messages do display instead of actual void
1. Once back in the main function:
```js
messages = runMarkdownLinkCheck();
if(filenameForOutput && (opts.quiet && containsDeadLinks(messages))) {
  for(result in results) {
    console.log(result.message)
  }
}
```

```js
containsDeadLinks(messages) {
for(message in messages) {
  if(message.status === 'dead') {
    return true;
  return false
}
```

**Comment by koppor** [comment]
Maybe add the option `-qq` for this.

**Comment by NicolasMassart** [comment]
Do you men nothing not even the file names?
If you use CLI and redirect stdout to `/dev/null` you will only have the error logs. That is `ERROR: 1 dead links found!` for instance. And of course noting if all links are ok.
However if you need also to have the file name in cas of broken link, it requires a change on https://github.com/tcort/markdown-link-check/blob/master/markdown-link-check#L167 to change log to error.

Last question: why do you need that? What is the use case? We usually use the command return code (0 or 1) to detect if error happened instead of trying to detect that from the output.

**Comment by NicolasMassart** [comment]
unless anyone comments otherwise, I will mark this one as wontfix.

**Comment by koppor** [comment]
Note that the error output is not helpful (see https://github.com/tcort/markdown-link-check/issues/87 for an explanation). As pointed out at https://github.com/tcort/markdown-link-check/issues/87#issuecomment-699017833, the solution is to know linux tools. `grep` is the best friend hier. Maybe `grep -B 1 ERROR`.
